/**
 * Package interfaz that includes the class MainJFrame, class CreateJPanel and DisplayPanel.
 * 
 * @author 
 * @version 3.0
 */
package interfaz;

import java.awt.Color;
import java.awt.Font;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JSeparator;
import javax.swing.LayoutStyle.ComponentPlacement;

import business.Person;

/**
 * Class DisplayJPanel
 * 
 * Creates the DisplayJPanel panel where personal profiles are loaded and
 * showed.
 * 
 * @author ankit
 * @version 3.0
 */
public class DisplayJPanel extends javax.swing.JPanel {

    static String personalCode;

    CreateJPanel department = new CreateJPanel(null);

    /**
     * Initialize all components included on DisplayJPanel panel.
     *
     * @param person
     */
    public DisplayJPanel(Person person) {
	initComponents();
	// this.person=person;

	// displayPerson(person);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    public void initComponents() {

	imageLabel = new javax.swing.JLabel();
	jLabel1 = new javax.swing.JLabel();
	jLabel2 = new javax.swing.JLabel();
	jLabel2.setForeground(new Color(50, 81, 255));
	jLabel2.setFont(new Font("Silom", Font.BOLD, 13));
	jLabel3 = new javax.swing.JLabel();
	jLabel3.setFont(new Font("Silom", Font.BOLD, 13));
	jLabel4 = new javax.swing.JLabel();
	jLabel4.setFont(new Font("Silom", Font.BOLD, 13));
	jLabel5 = new javax.swing.JLabel();
	jLabel5.setFont(new Font("Silom", Font.BOLD, 13));
	jLabel6 = new javax.swing.JLabel();
	jLabel6.setFont(new Font("Silom", Font.BOLD, 13));
	jLabel7 = new javax.swing.JLabel();
	jLabel7.setFont(new Font("Silom", Font.BOLD, 13));
	jLabel8 = new javax.swing.JLabel();
	jLabel8.setFont(new Font("Silom", Font.BOLD, 13));
	jLabel9 = new javax.swing.JLabel();
	jLabel9.setFont(new Font("Silom", Font.BOLD, 13));
	jLabel10 = new javax.swing.JLabel();
	jLabel10.setFont(new Font("Silom", Font.BOLD, 13));
	jLabel11 = new javax.swing.JLabel();
	jLabel11.setFont(new Font("Silom", Font.BOLD, 13));
	ssnTextField = new javax.swing.JTextField();
	emailTextField = new javax.swing.JTextField();
	phoneTextField = new javax.swing.JTextField();
	dobTextField = new javax.swing.JTextField();
	nameTextField = new javax.swing.JTextField();
	perCodeTextField = new javax.swing.JTextField();
	geoTextField = new javax.swing.JTextField();
	bankTextField = new javax.swing.JTextField();
	dosTextField = new javax.swing.JTextField();
	departmTextField = new javax.swing.JTextField();
	imageUrlTextField = new javax.swing.JTextField();
	imageUrlTextField.setVisible(false);

	imageLabel.setBackground(new java.awt.Color(102, 102, 102));
	imageLabel.setOpaque(true);

	jLabel2.setText("Personal code:");
	jLabel3.setText("Name:");
	jLabel4.setText("Geographic Data:");
	jLabel5.setText("Date of Birth:");
	jLabel6.setText("Phone:");
	jLabel7.setText("Date of start:");
	jLabel8.setText("Email:");
	jLabel9.setText("Social Security Number:");
	jLabel10.setText("Bank Account Number:");
	jLabel11.setText("Department: ");

	bankTextField.setEditable(false);
	ssnTextField.setEditable(false);
	emailTextField.setEditable(false);
	geoTextField.setEditable(false);
	phoneTextField.setEditable(false);
	phoneTextField.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		emailTextFieldActionPerformed(evt);
	    }
	});

	dosTextField.setEditable(false);
	dobTextField.setEditable(false);
	nameTextField.setEditable(false);
	perCodeTextField.setEditable(false);
	departmTextField.setEditable(false);

	jLabel1.setFont(new Font("Silom", Font.BOLD, 27)); // NOI18N
	jLabel1.setText("Display Profile");

	separator = new JSeparator();

	/**
	 * Generates group layout with all components.
	 */
	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	layout.setHorizontalGroup(layout.createParallelGroup(Alignment.TRAILING)
		.addGroup(layout.createSequentialGroup().addGap(249)
			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 223, GroupLayout.PREFERRED_SIZE)
			.addContainerGap(349, Short.MAX_VALUE))
		.addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(Alignment.TRAILING)
			.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(separator,
				GroupLayout.PREFERRED_SIZE, 699, GroupLayout.PREFERRED_SIZE))
			.addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(
					imageUrlTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
				.addGroup(layout.createSequentialGroup().addGap(57).addGroup(layout
					.createParallelGroup(Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(jLabel7)
						.addPreferredGap(ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
						.addComponent(dosTextField, GroupLayout.PREFERRED_SIZE, 244,
							GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup().addComponent(jLabel6)
						.addPreferredGap(ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
						.addComponent(phoneTextField, GroupLayout.PREFERRED_SIZE, 244,
							GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
						.addPreferredGap(ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
						.addComponent(perCodeTextField, GroupLayout.PREFERRED_SIZE, 244,
							GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup().addComponent(jLabel5)
						.addPreferredGap(ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
						.addComponent(dobTextField, GroupLayout.PREFERRED_SIZE, 244,
							GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
							.addComponent(jLabel8).addComponent(jLabel3)
							.addComponent(jLabel9).addComponent(jLabel10))
						.addPreferredGap(ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
							.addComponent(bankTextField, 244, 244, 244)
							.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, 244,
								GroupLayout.PREFERRED_SIZE)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(emailTextField,
									GroupLayout.PREFERRED_SIZE, 244,
									GroupLayout.PREFERRED_SIZE)
								.addComponent(ssnTextField, 244, 244, 244))))
					.addGroup(layout.createSequentialGroup().addComponent(jLabel4)
						.addPreferredGap(ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
						.addComponent(geoTextField, GroupLayout.PREFERRED_SIZE, 244,
							GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup()
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(jLabel11)
						.addPreferredGap(ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
						.addComponent(departmTextField, GroupLayout.PREFERRED_SIZE, 244,
							GroupLayout.PREFERRED_SIZE)))))
				.addGap(18)
				.addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 246, GroupLayout.PREFERRED_SIZE)))
			.addGap(77)));
	layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
		.addGap(66).addComponent(jLabel1).addGap(26)
		.addGroup(layout.createParallelGroup(Alignment.LEADING)
			.addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE)
			.addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
					.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(jLabel3).addGap(3))
				.addGroup(layout.createSequentialGroup()
					.addComponent(perCodeTextField, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED).addComponent(nameTextField,
						GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE)))
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(geoTextField,
							GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
							GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup().addGap(11).addComponent(jLabel4)))
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(dobTextField,
							GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
							GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup().addGap(11).addComponent(jLabel5)))
				.addGap(11)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel6)
					.addComponent(phoneTextField, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
					.addComponent(emailTextField, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addComponent(jLabel8))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
					.addComponent(ssnTextField, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addComponent(jLabel9))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
					.addComponent(bankTextField, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addComponent(jLabel10))
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(dosTextField,
							GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
							GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup().addGap(10).addComponent(jLabel7)))
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(
							departmTextField, GroupLayout.PREFERRED_SIZE,
							GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createSequentialGroup().addGap(10).addComponent(jLabel11)))))
		.addPreferredGap(ComponentPlacement.RELATED)
		.addComponent(imageUrlTextField, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE).addGap(26)
		.addComponent(separator, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
			GroupLayout.PREFERRED_SIZE)
		.addContainerGap(29, Short.MAX_VALUE)));
	this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailTextFieldActionPerformed
    }// GEN-LAST:event_emailTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Declaration of JTextField ssnTextField object.
     */
    public static javax.swing.JTextField ssnTextField;

    /**
     * Declaration of JTextField geoTextField object.
     */
    public static javax.swing.JTextField geoTextField;

    /**
     * Declaration of JTextField phoneTextFieldb object.
     */
    public static javax.swing.JTextField phoneTextField;

    /**
     * Declaration of JTextField dosTextField object.
     */
    public static javax.swing.JTextField dosTextField;

    /**
     * Declaration of JTextField nameTextField object.
     */
    public static javax.swing.JTextField nameTextField;

    /**
     * Declaration of JLabel imageLabel object.
     */
    public static javax.swing.JLabel imageLabel;

    /**
     * Declaration of JLabel jLabel11 object.
     */
    private javax.swing.JLabel jLabel1;

    /**
     * Declaration of JLabel jLabel12 object.
     */
    private javax.swing.JLabel jLabel2;

    /**
     * Declaration of JLabel jLabel13 object.
     */
    private javax.swing.JLabel jLabel3;

    /**
     * Declaration of JLabel jLabel14 object.
     */
    private javax.swing.JLabel jLabel4;

    /**
     * Declaration of JLabel jLabel15 object.
     */
    private javax.swing.JLabel jLabel5;

    /**
     * Declaration of JLabel jLabel16 object.
     */
    private javax.swing.JLabel jLabel6;

    /**
     * Declaration of JLabel jLabel17 object.
     */
    private javax.swing.JLabel jLabel7;

    /**
     * Declaration of JLabel jLabel18 object.
     */
    private javax.swing.JLabel jLabel8;

    /**
     * Declaration of JLabel jLabel9 object.
     */
    private javax.swing.JLabel jLabel9;

    /**
     * Declaration of JLabel jLabel10 object.
     */
    private javax.swing.JLabel jLabel10;

    /**
     * Declaration of JLabel jLabel11 object.
     */
    private javax.swing.JLabel jLabel11;

    /**
     * Declaration of JTextField bankTextField object.
     */
    public static javax.swing.JTextField bankTextField;

    /**
     * Declaration of JTextField perCodeTextField object.
     */
    public static javax.swing.JTextField perCodeTextField;

    /**
     * Declaration of JTextField dobTextField object.
     */
    public static javax.swing.JTextField dobTextField;

    /**
     * Declaration of JTextField emailTextField object.
     */
    public static javax.swing.JTextField emailTextField;

    /**
     * Declaration of JTextField departmTextField object.
     */
    public static javax.swing.JTextField departmTextField;

    /**
     * Declaration of JTextField imageUrlTextField object.
     */
    public static javax.swing.JTextField imageUrlTextField;

    /**
     * Declaration of JSeparator separator object.
     */
    private JSeparator separator;
}